### ISSUE TITLE
Linux engine passes applysql.cmd as applysql.vbs to dmtransfer

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#102]

**Comment by pgibbs-openmake** [comment]
That's because $EXT will expand to ".vbs" for Windows Targets (look in the table dm_servertype). dmtransfer will then call winlib to do the transfer. winlib (and winlib-unix) will then "stat" the file and - if it doesn't exist - will replace the extension, trying .cmd, .bat and .exe in sequence until it finds a matching file.

So the fact that applysql.vbs is being passed to dmtransfer is not an issue since winlib/winlib-unix will then find the correct file by substituing the file extension.

**Comment by sbtaylor15** [comment]
Ok, sounds good.
