### ISSUE TITLE
Copying an Application Involves too Many Steps

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#155]
When copying an Application from one Domain to another, an error appears informing the user about any Components that belong to the Application, and won't allow the Application to be copied until the Component(s) are copied to the same Domain as the Application. When attempting to copy the Component(s), errors regarding any Actions belonging to the Components are then displayed and those Actions have to be copied over before the Component(s) can be created. This goes on and on until everything is copied over. It would be nice to just have everything created at once whenever an Application is copied from one Domain to another. Also, maybe when copying just a Component, or an entire Domain?

**Comment by pgibbs-openmake** [comment]
This is working as designed. It depends on where the components, applications and actions are defined in the domain tree. If they are declared at a higher level (which they generally should be) then copying an application or component does not flag an issue. If the target domain does not have access to the component (or the component does not have access to the action) then an error is thrown. It is not desirable to simply copy the action (since we would now have two actions) or copy the component (since we would have two copies of the same component). In such a situation, the user would *probably* elect to move the component or action to a higher domain thereby allowing it to be shared between the original application/component and the new copy.

**Comment by rightker** [comment]
Understood, closing this issue.
