### ISSUE TITLE
Single Change Request added to Component Displays in Burndown Chart on Far Right

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#169]
In a Component with no Change Requests; Change Requests tab -> Click plus sign to add a Change Request -> Select a CR by clicking on a checkbox -> Click OK to put window away, notice the newly added CR in the burndown chart is on the far right, and a lot of the calendar is in the past to the left, which tells us nothing. Other Change Request tabs which contain Open and Closed CRs have everything centered. Also, the red line is unavailable, since it's off the window to the right. Scrolling the mouse wheel helps to locate it, but it's unwieldy.

**Comment by pgibbs-openmake** [comment]
"_**Other Change Request tabs which contain Open and Closed CRs have everything centered"**_ 
This is not true (or shouldn't be) The described behaviour is "as designed" for both applications and components. "Now" is always on the right-hand side of the display since there is no information on future change requests.

**_"A lot of the calendar is in the past to the left"_**
that is exactly what is required.

**_"which tells us nothing"_**
on the contrary, it tells you _everything_ as this shows you how quickly change requests are being added and/or closed. That's the burn down chart.

There is nothing - and _cannot_ be anything - beyond today that will tell us anything. That is why newly added change requests are added on the right-hand side since that point on the chart is "now".

**Comment by rightker** [comment]
Very good, thanks for the explanation(s). Closing this issue.
