### ISSUE TITLE
Copy Version Task is No Longer in the List When Creating a New Task

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#47]
Domains menu -> Domains tab -> Right click on in the Tasks in This Domain area, notice that the Copy Task is no longer in the list of Tasks

**Comment by pgibbs-openmake** [comment]
No, it’s not. It’s been removed (it never made sense anyway since an application or app version can only ever be in one domain at a time).

P.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Wow, fast response. OK, sounds good, closing this issue.
