### ISSUE TITLE
Remove Task Doesn't Appear in Drop Down List

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#48]
Domains menu -> Domains tab -> Click on a Domain -> Tasks tab -> Right click on a Domain -> Select 'Add Remove Application Task' from the drop down list -> Click on the new Task in the 'Tasks in this Domain' list -> Click on the pencil icon to edit the new Task and fill in fields (optional) -> Deploy menu -> Applications tab -> Right click on an Application -> Notice the new Remove Task does not appear in the list, but there is a 'Delete this Application Base Version' in the list. This appears for every Domain whether or not there is a Remove Task in the Domain or not.

**Comment by pgibbs-openmake** [comment]
This works for me. Are you sure you added “Everyone” (or whoever) to the “Group Access” (because that’s not stated in the steps below). If you don’t have access, you won’t see the task regardless of whether you have admin rights or not.

P.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by pgibbs-openmake** [comment]
Also, bear in mind that “Remove Application” is only application to BASE applications. Right clicking on an application VERSION will not show the remove task.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Good catch, I didn't know that. Updating the online docs to show that only Application Base Versions are not affected by Remove Tasks.
