### ISSUE TITLE
Need to show Procedures, Actions, etc. in Tree When Below Current View

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#59]
If  the User right clicks an object in a Workflow and selects "Goto this [object]", or clicks on the breadcrumbs at the bottom of the window to navigate back to an object in the tree, and the object in the tree structure is below the visible part of it, the tree does not shift or scroll to show the object in the tree. Can we do this? I think there was a previous discussion concerning this, but with all of the Ansible Procedures in Release Engineer now it's becoming more important to look into this.

**Comment by pgibbs-openmake** [comment]
This should work in the latest code base in git - problem was caused by categories appearing in the tree view.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Build 425. Still doesn't work.

**Comment by sbtaylor15** [comment]
Retest, categories weren't taken into account.  Scrolling treeview still not implemented

**Comment by rightker** [comment]
Highlights the correct object but still doesn't scroll. We're not going to deal with this until after 7.6. Closing this issue.
