### ISSUE TITLE
Trouble Trying to Change a Checkbox to a Text Field

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#63]
Create a Procedure of Kind "Procedure provided by local external script or program" with a text field and a checkbox. Save. Use it with a batch file with the following contents on the localhost just for simplicity.

MKDIR %1
MKDIR %2

Put the Procedure into an Action, then notice that it's a text and checkbox, oops they both need to be text boxes, so go back and make that change in the Procedure. Put the Procedure into the Action and put values into the fields i.e. 'testThis', 'testThat'. Put the Action into the PreAction of the Component and deploy the Application. Go to the Timeline and look at the log:

...
INFO: Checked out 2 file(s) from repository "FHFiles"

C:\Windows\TEMP\tdm.294.2>MKDIR c:\"testThis" 

C:\Windows\TEMP\tdm.294.2>MKDIR c:\"" 
Access is denied.
...

Notice that instead of c:\testThat, it tries to create c:\

The "Access is denied" message is related to another problem with trailing slashes, but notice that the "testThat" has been lost, probably because of the change of the check box to a text box.

**Comment by pgibbs-openmake** [comment]
Changing any attribute of a function/procedure argument (for example changing the type from checkbox to entry or vice-versa) would set the switch/negswitch values to a null-length string rather than a NULL value. This would cause the engine to insert a zero-length quoted parameter before the passed parameter (as it would assume there was a switch present) - this causes the 2nd parameter to become the 3rd and the 2nd parameter to be a zero-length string.
    
Changed the logic so that if the switch is zero-length then the value updated is NULL rather than a zero-length string.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Now having trouble testing this because of an unrelated error msg.

**Comment by sbtaylor15** [comment]
Fixed, retest

**Comment by rightker** [comment]
Fixed, closing this issue.
