### ISSUE TITLE
ip address does not work for host name in server

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#83]
Putting in the host name and hitting test on the status tab works.  But ip address does not work.
./dm -usr admin -checkserver 101

returns database erorr when using ip address.  DB Error in Execute ERROR: invalid byte sequence for an encoding "UTF8"  for the update of serverstatus table.

**Comment by pgibbs-openmake** [comment]
Problem was caused by an error in the Linux implementation of "ping" which did not return the ipaddress into char **szad if the hostname was an IPv4 address.

Problem now, is that the IP address is returned correctly but on FIRST connection sshexec fails with:
/opt/release-engineer/engine/lib/sshexec: line 52: /root/.ssh/known_hosts: No such file or directory

Subsequent test works correctly. It looks like on first pass $HOME/.ssh may not necessarily exist.

**Comment by sbtaylor15** [comment]
Fixed in build from 4/13.
